<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>


  
  <link rel="stylesheet" href="stdlayout.css" tppabs="http://caterpillar.onlyfun.net/Gossip/CppGossip/css/stdlayout.css" type="text/css">


  
  <link rel="stylesheet" href="print.css" tppabs="http://caterpillar.onlyfun.net/Gossip/CppGossip/css/print.css" type="text/css">


  
  <meta content="text/html; charset=Big5" http-equiv="content-type">

  
  <title>簡介例外處理</title>
</head>


<body>


<h3><a href="javascript:if(confirm('http://caterpillar.onlyfun.net/Gossip/index.html  \n\nThis file was not retrieved by Teleport Pro, because it is addressed on a domain or path outside the boundaries set for its Starting Address.  \n\nDo you want to open it from the server?'))window.location='http://caterpillar.onlyfun.net/Gossip/index.html'" tppabs="http://caterpillar.onlyfun.net/Gossip/index.html">From
Gossip@caterpillar</a></h3>


<h1><a href="CppGossip.html" tppabs="http://caterpillar.onlyfun.net/Gossip/CppGossip/CppGossip.html">C++
Gossip:&nbsp;簡介例外處理</a></h1>


<table style="text-align: left; width: 946px; height: 32px;" border="0" cellpadding="0" cellspacing="0">


  <tbody>


    <tr>


      <td style="width: 676px; vertical-align: top;"> <small>
撰寫一個程式從某些角度來說其實並不困難，一個程式的撰寫的過程中，避免程式執行時的錯誤，往往佔了程式開發時程的絕大多數時間，有很多方法可以避免程式
執行時的錯誤，這也與您所使用的程式語言有關，C++則提供了「例外處理」（Exception handling）機制。 <br>

      <br>


在之前還沒有學習例外處理之前，如果要撰寫一個除法程式，並由使用者輸入除數與被除數，由於被除數除以0沒有意義，所以之前可能必須像以下這樣避免錯誤：
      <br>

      </small>

      
      <div style="margin-left: 40px; font-family: Courier New,Courier,monospace;"><small><span style="font-weight: bold;">if(b != 0) &nbsp;{</span><br style="font-weight: bold;">


      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
cout &lt;&lt; "a/b = " </span><br style="font-weight: bold;">


      <span style="font-weight: bold;">&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;&lt;
double(a / b) </span><br style="font-weight: bold;">


      <span style="font-weight: bold;">&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&lt;&lt;
endl;</span><br style="font-weight: bold;">


      <span style="font-weight: bold;">}</span><br style="font-weight: bold;">


      <span style="font-weight: bold;">else {</span><br style="font-weight: bold;">


      <span style="font-weight: bold;">&nbsp;&nbsp; cout
&lt;&lt; "除數不能為0" </span><br style="font-weight: bold;">


      <span style="font-weight: bold;">&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &lt;&lt; endl;</span><br style="font-weight: bold;">


      <span style="font-weight: bold;">}</span><br>


      </small></div>


      <small><br>


這樣的方式過去在一些程式語言中會很常被利用，利用判斷式來避免錯誤的發生，然而這樣的方式會讓錯誤處理與程式的處理邏輯混在一起，使得程式難以閱讀，在
C++中可以利用例外處理機制，將程式邏輯與錯誤處理適當的分開撰寫，增加程式的可讀性與安全性。 <br>

      <br>


C++中的例外處理使用三個關鍵字來進行：try、catch、throw，其語法架構如下： <br>

      </small>

      
      <div style="margin-left: 40px;"><small><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">try
{ </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
// 程式 </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
throw Type </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}
catch(Type 1) { </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
// 錯誤處理 </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}
catch(Type 2) { </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
// 錯誤處理 </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}</span><br>


      </small></div>


      <small><br>


在程式中，當檢查到錯誤發生時，使用throw丟出一個數值，這個數值可能是一個整數、浮點數、字串或是物件，丟出數值之後，程式邏輯會離開丟出點，然後
開始比對catch中設定的資料型態，如果找到對應的型態，就執行該區塊中的程式碼，執行完後就離開整個try...catch，這有些類似switch
語法，執行完對應的case之後設定break來離開switch區塊。 <br>

      <br>


先以一個簡單的程式作示範： </small>
      <br>


      <br>


      
      <pre>#include &lt;iostream&gt; <br>using namespace std; <br><br>int main() { <br>    int a = 0;<br>    int b = 0; <br><br>    cout &lt;&lt; "請輸入被除數: "; <br>    cin &gt;&gt; a; <br>     cout &lt;&lt; "請輸入除數: "; <br>    cin &gt;&gt; b;<br><br>    try { <br>        if(b == 0) <br>            throw 0; <br>        cout &lt;&lt; "a / b = " <br>             &lt;&lt; static_cast&lt;double&gt;(a) / b <br>             &lt;&lt; endl; <br>    } <br>    catch(int err) { <br>        cout &lt;&lt; "除數為: " &lt;&lt; err &lt;&lt; endl; <br>        cout &lt;&lt; "結果無限大" &lt;&lt; endl; <br>    } <br> <br>    return 0;<br>}</pre>


      <span class="postbody"><br>

      <small>
執行結果：</small></span><br>


      
      <table style="text-align: left; width: 100%;" border="0" cellpadding="2" cellspacing="2">


        <tbody>


          <tr>


            <td style="background-color: rgb(0, 0, 0);"><small><span style="color: rgb(255, 255, 255);">請輸入被除數: 10 <br>


請輸入除數: 0 <br>


除數為: 0 <br>


結果無限大</span></small><span style="color: rgb(255, 255, 255);"><br>


            </span></td>


          </tr>


        
        </tbody>
      
      </table>


      <br>

      <small>
當使用者輸入除數為0時，程式會檢查出來，此時丟出一個整數錯誤代碼，程式中catch有一個捕捉整數的區塊，當捕捉到錯誤代碼時，就會執行catch區
塊中的程式碼。 <br>

      <br>


發生錯誤時，執行哪一段catch區塊是由您所丟出的資料型態而定，丟出整數時就由設定catch整數的區塊捕捉，丟出浮點數時就用設定catch浮點數
的區塊捕捉，您也可以直接丟出一個代表錯誤訊息的字串，以說明錯誤的原因，例如： <br>

      </small>

      <br>


      
      <pre>#include &lt;iostream&gt; <br>using namespace std;<br><br>int main() { <br>    int a = 0;<br>    int b = 0;<br><br>    cout &lt;&lt; "請輸入被除數: "; <br>    cin &gt;&gt; a; <br>    cout &lt;&lt; "請輸入除數: "; <br>    cin &gt;&gt; b;<br><br>    try { <br>        if(b == 0) <br>            throw "發生除零的錯誤"; <br>        cout &lt;&lt; "a / b = " <br>             &lt;&lt; static_cast&lt;double&gt;(a) / b <br>             &lt;&lt; endl; <br>    } <br>    catch(int err) { <br>        cout &lt;&lt; "除數為: " &lt;&lt; err &lt;&lt; endl; <br>        cout &lt;&lt; "結果無限大" &lt;&lt; endl; <br>    } <br>    catch(const char* str) { <br>        cerr &lt;&lt; "錯誤: " &lt;&lt; str &lt;&lt; endl; <br>    } <br> <br>    return 0;<br>}</pre>


      <span class="postbody"><br>

      <small>
執行結果：</small></span><br>


      
      <table style="text-align: left; width: 100%;" border="0" cellpadding="2" cellspacing="2">


        <tbody>


          <tr>


            <td style="background-color: rgb(0, 0, 0);"><small><span style="color: rgb(255, 255, 255);">請輸入被除數: 9 <br>


請輸入除數: 0 <br>


錯誤: 發生除零的錯誤</span></small><span style="color: rgb(255, 255, 255);"><br>


            </span></td>


          </tr>


        
        </tbody>
      
      </table>


      <br>

      <small>
如果打算在catch中處理完例外之後，再度將例外丟出，則再使用throw即可，例如：<br>

      </small>
      
      <div style="margin-left: 40px;"><small><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">catch(...)
{ </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
// 處理例外 </span><br style="font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;
&nbsp; throw; // 再度丟出</span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}</span><br>


      </small></div>


      <small><br>


如果您丟出例外而catch中並沒有相對捕捉該例外的區塊，則程式會呼叫標準函式庫中的terminate()函式，而預設terminate()會呼叫
abort()函式來終止程式。 <br>

      <br>


如果您想捕捉所有型態的例外，您可以使用catch(...)，通常這會放在所有catch之後，以捕捉所有尚未考慮到的例外狀況：<br>

      </small>

      
      <div style="margin-left: 40px;"><small><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">catch(...)
{ </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
// 處理所有的例外 </span><br style="font-weight: bold; font-family: Courier New,Courier,monospace;">


      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}</span><br>


      </small></div>


      <small><br>


事實上，C++的例外處理鼓勵您自訂例外類別階層體系，將這些類別可以當作catch的資料型態設定條件，以應付各種不同的錯誤處理。 </small> </td>


      <td style="width: 250px; text-align: center; vertical-align: top;"><!-- adsense for content-->
      
      <script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      
      <script type="text/javascript" src="show_ads.js" tppabs="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><br>


<!-- adsense for content end--><br>


<!-- adsense for content-->
      
      <script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      
      <script type="text/javascript" src="show_ads.js" tppabs="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><!-- adsense for content end--></td>


    </tr>


  
  </tbody>
</table>


<br>

<br>


<br>


</body>
</html>
